### ISSUE TITLE
[Android] 混合页面跳转返回时pop的问题

### ISSUE THREAD

**Issue by jeff-liu14** [flutter-thrio/thrio#100]
现在有如下调用栈：

```
Native1 -> Flutter1 -> Flutter2 -> Flutter3  -> (返回到Native1)

Native1 : 此页面为原生页面，未注册在Thrio路由中（此页面可能为RN页面或Web页面所以无法注册到Thrio）
```
问题描述：

调用流程为如上，Flutter1-3 均接入到Thrio中，现在需要在页面Flutter3 页面时直接返回到Native1页面，现有的pop方法仅支持pop当前栈顶原素，popTo 方法只支持注册在Thrio中的页面，remove方法和pop方法类似，无法同时移除多个栈内Activity

期待：

_开放Thrio内部栈管理_ **OR** _提供删除多个页面和清除栈内页面的方法_

**Comment by foxsofter** [comment]
最快的办法，直接remove到 Flutter1，再pop，效果应该没区别，唯一的问题是，你是否能获取这这些 url，如果这些url是变动的话，也是问题

**Comment by foxsofter** [comment]
我在考虑给 thrio 添加 initialRoute，这样底部的页面也可以索引到

**Comment by jeff-liu14** [comment]
> 我在考虑给 thrio 添加 initialRoute，这样底部的页面也可以索引到

我差不多也是这个意思，我自己管理activity生命周期，你需要在ThrioActivity 里给我开放一个当前的路由的字段

```
object FlutterActivityStack {
    data class FlutterStack(
        val routePath: String = "",
        val activity: WeakReference<ThrioActivity?>? = null
    )

    private var myApplication: Application? = null
    private var mActivityStack: MutableList<FlutterStack> = mutableListOf()

    fun registerLifecycle(application: Application) {
        this.myApplication = application
        application.registerActivityLifecycleCallbacks(object :
            Application.ActivityLifecycleCallbacks {
            override fun onActivityPaused(activity: Activity?) {
            }

            override fun onActivityResumed(activity: Activity?) {
            }

            override fun onActivityStarted(activity: Activity?) {
                if (activity is ThrioActivity) {
                    Log.d("onActivityStarted", activity.dartEntrypointFunctionName)
                    Log.d("onActivityStarted", activity.initialRoute)
                    mActivityStack.add(
                        FlutterStack(
                            routePath = "这边在ThrioActivity中提供一个可以获取当前路由的字段",
                            activity = WeakReference(activity)
                        )
                    )
                }
            }

            override fun onActivityDestroyed(activity: Activity?) {
            }

            override fun onActivitySaveInstanceState(activity: Activity?, outState: Bundle?) {
            }

            override fun onActivityStopped(activity: Activity?) {
            }

            override fun onActivityCreated(activity: Activity?, savedInstanceState: Bundle?) {
            }
        })
    }
}
```

**Comment by jeff-liu14** [comment]
> 最快的办法，直接remove到 Flutter1，再pop，效果应该没区别，唯一的问题是，你是否能获取这这些 url，如果这些url是变动的话，也是问题

在中间Flutter1 - 3 之前可能会有穿插原生的栈所以这套流程可能还是有问题

**Comment by foxsofter** [comment]
> > 最快的办法，直接remove到 Flutter1，再pop，效果应该没区别，唯一的问题是，你是否能获取这这些 url，如果这些url是变动的话，也是问题
> 
> 在中间Flutter1 - 3 之前可能会有穿插原生的栈所以这套流程可能还是有问题

那就用popTo -> flutter1，然后再 pop，popTo会处理掉穿插的原生的页面，需要注意所有的路由方法如果连续用的话，都要等上一个的reusult返回再调

**Comment by foxsofter** [comment]
> > 我在考虑给 thrio 添加 initialRoute，这样底部的页面也可以索引到
> 
> 我差不多也是这个意思，我自己管理activity生命周期，你需要在ThrioActivity 里给我开放一个当前的路由的字段
> 
> ```
> object FlutterActivityStack {
>     data class FlutterStack(
>         val routePath: String = "",
>         val activity: WeakReference<ThrioActivity?>? = null
>     )
> 
>     private var myApplication: Application? = null
>     private var mActivityStack: MutableList<FlutterStack> = mutableListOf()
> 
>     fun registerLifecycle(application: Application) {
>         this.myApplication = application
>         application.registerActivityLifecycleCallbacks(object :
>             Application.ActivityLifecycleCallbacks {
>             override fun onActivityPaused(activity: Activity?) {
>             }
> 
>             override fun onActivityResumed(activity: Activity?) {
>             }
> 
>             override fun onActivityStarted(activity: Activity?) {
>                 if (activity is ThrioActivity) {
>                     Log.d("onActivityStarted", activity.dartEntrypointFunctionName)
>                     Log.d("onActivityStarted", activity.initialRoute)
>                     mActivityStack.add(
>                         FlutterStack(
>                             routePath = "这边在ThrioActivity中提供一个可以获取当前路由的字段",
>                             activity = WeakReference(activity)
>                         )
>                     )
>                 }
>             }
> 
>             override fun onActivityDestroyed(activity: Activity?) {
>             }
> 
>             override fun onActivitySaveInstanceState(activity: Activity?, outState: Bundle?) {
>             }
> 
>             override fun onActivityStopped(activity: Activity?) {
>             }
> 
>             override fun onActivityCreated(activity: Activity?, savedInstanceState: Bundle?) {
>             }
>         })
>     }
> }
> ```

我会提供以下方法，类似iOS端，不过会返回 PageRoute，main分支上已经存在了，可以获取到最后一个Activity的最后一个PageRoute
```kotlin
    fun lastRoute(url: String? = null): PageRoute?
```

**Comment by foxsofter** [comment]
待完善 #101
