### ISSUE TITLE
Android设备运行Example冷启动Flutter页面会有个黑屏的过程

### ISSUE THREAD

**Issue by phoenixsky** [flutter-thrio/thrio#107]
![冷启动黑屏](http://blogimgs.phoenixsky.cn//picgo/IMG_00871.gif)

http://blogimgs.phoenixsky.cn//picgo/IMG_00871.gif

视频做了一个慢动作的处理。
demo,中第一次打开flutter页面，黑屏还是比较明显的

代码：issue时新拉的main分支

**Comment by foxsofter** [comment]
从 startActivity 到 onCreate，没法加快了，release下面应该几乎看不到了，你可以自己加一个闪屏页

**Comment by phoenixsky** [comment]
试了下release下确实几乎没有了。
你说的这个加闪屏页的话，具体在哪里处理？
我本来想的是，在app启动适合，就在splash页面把flutter engine给启动了。

**Comment by foxsofter** [comment]
这里可能还是可以再加快些，不过目前的逻辑依赖于 Activity 的实例，引擎其实是已经提前启动了

**Comment by foxsofter** [comment]
做了优化，现在应该是看不到黑屏了，pub 1.2.1
