### ISSUE TITLE
swift项目中导入thrio之后，侧滑返回不可用，且多次侧滑之后会崩溃

### ISSUE THREAD

**Issue by wendeqiang** [flutter-thrio/thrio#114]
我也尝试在项目中通过navigationController?.interactivePopGestureRecognizer?.isEnabled = true关闭系统的侧滑返回，但是依然没有作用

**Comment by foxsofter** [comment]
我刚加了 issue template，你重新编辑下你的 issue，不然这样提没办法解决的
