### ISSUE TITLE
建议增加页面路由跳转params参数支持dart类对象

### ISSUE THREAD

**Issue by xiazhouquan** [flutter-thrio/thrio#115]
**Describe the bug**

目前thrio路由之间传递参数是需要序列化的，直接传入dart类对象，会因为出现method channel解析出错，所以flutter上层只能先进行json序列化，用到的页面在进行反序列化。建议纯flutter之间增加直接传递对象的支持，这样可以减少UI层定义model对象的json序列化实现。此问题之前群里面讨论过，待后续再优化。目前有尝试过一个项目即使用thrio以及flutter的路由功能，纯flutter的页面直接进行对象传递，非fluuter用thrio的序列化对象传递，但是两套路由共存会有返回冲突，维护起来很麻烦。

thrio 版本：1.0.0
flutter sdk版本：1.22.2

**To Reproduce**
1. 定义dart model类，比如
class CoinBalance {
final String _symbol;
CoinBalance(this._symbol);
} 
2. 实例化对象
var coinBalance = CoinBalance("BTC")
3. 页面跳转,传入coinBalance
ThrioNavigator.push(url:"/test", params: coinBalance, poppedResult: poppedResult);

4. thiro chanel出错

**Expected behavior**
暂无

**Flutter Doctor**

[✓] Flutter (Channel stable, 1.22.2, on Mac OS X 10.15.5 19F101, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Community Edition (version 2020.1.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Proxy Configuration
[✓] Connected device (1 available)

**OS & Device**
 - Device: [huawei]
 - OS: [android]
 - Version [6.0]

**Error logs**
暂无

**Comment by foxsofter** [comment]
这个实现起来不麻烦，问题在于 Flutter -> Flutter 之间传递参数也会经过原生端，也需要进行序列化和反序列化，当然这没有任何问题，只是 dart 不支持反射，实现起来不够优雅，在 dart 端需要提供注册序列化和反序列化器的能力，这在 ThrioModule 上扩展一个就可以做到，但很难统一json的库，不同的项目会引入不同的json库，这是一直没有加上这个能力的原因。

在考虑将json库的能力交给使用者来提供，有时间我来实现下。

**Comment by foxsofter** [comment]
dev 分支已经支持 flutter <--> flutter 之间传递复杂类型了
