### ISSUE TITLE
建议2.0后续版本增加关于无context弹框的处理

### ISSUE THREAD

**Issue by xiazhouquan** [flutter-thrio/thrio#116]
提出原因：
目前大多数弹框都需要context，系统或者第三方库，在常规页面弹框没有问题，但在Android上处理返回键的时候需要特殊处理下willpopscope。

一些特殊场合：
比如模块之间通讯，根据业务逻辑进行判断，会用到弹框处理，此时无context就非常方便了。

现有一个项目弹框或者action sheet是无context处理的比较好用，[getx](https://github.com/jonataslaw/getx)，通过现实项目集成使用一段时间发现的一个问题Get.dialog后对按返回按键，会导致原始的导航返回（使用的thrio pop方法）失效，解决办法是在有弹框的页面使用willpopscope进行弹框处理：

WillPopScope(
      onWillPop: () {
        if (Get.isBottomSheetOpen) {
//关闭弹框
          Get.close(1);
          return Future.value(false);
        }
//没有弹框，返回交由thrio继续处理，完成返回
        return Future.value(true);
      },

由于弹框还是比较常见的功能，看到Get项目处理还是很优秀，并且thrio有目标要做状态管理，看看作者的规划是否能够提供类似集成了导航弹框的方法，集成到thrio。这样就是flutter混合开发的一个即常用又核心大而全的库了。

**Comment by foxsofter** [comment]
有时间再来加吧，这个其实也还好，不是太麻烦

**Comment by foxsofter** [comment]
pub 1.5.0，thrio 就支持 Navigator 了，不存在需要 WillPopScope 拦截的问题了，无 context 对话框本身并不是一个好的做法，如果有这种需求，可自行转发
