### ISSUE TITLE
UIImagePickerController 导航栏被显示出来了

### ISSUE THREAD

**Issue by DavidWu109** [flutter-thrio/thrio#119]
![image](https://user-images.githubusercontent.com/15978657/100993122-f9a70480-358f-11eb-8685-bcf58969c1cf.png)

UIImagePickerController 系统是默认隐藏导航栏的，由于这个页面的 thrio_hidesNavigationBar_ 这个字段没有赋值，所以默认为false。
在执行下列代码时会把导航栏显示出来
self.navigationController.navigationBarHidden = self.thrio_hidesNavigationBar_.boolValue;

**Comment by foxsofter** [comment]
你改成下面代码试试
```objc
    if (self.thrio_hidesNavigationBar_ && self.thrio_hidesNavigationBar_.boolValue != self.navigationController.navigationBarHidden) {
        self.navigationController.navigationBarHidden = self.thrio_hidesNavigationBar_.boolValue;
    }
```
