### ISSUE TITLE
这个如何再已有的原生项目集成

### ISSUE THREAD

**Issue by xieqi520** [flutter-thrio/thrio#125]
oc里面找不到thrio的库文件

**Comment by foxsofter** [comment]
flutter module搜一搜

**Comment by xieqi520** [comment]
[!] There are multiple dependencies with different sources for `my_flutter` in `Podfile`:

- my_flutter (from `../my_flutter/.ios/Flutter/.symlinks/my_flutter/ios`)
- my_flutter (from `../my_flutter/.ios/Flutter`)
在my_flutter里面添加thrio之后，在pod原生工程的，就报这个错误了，

**Comment by foxsofter** [comment]
这句话不是已经告诉你了嘛，different sources，看看你的podfile，多个source

**Comment by xieqi520** [comment]
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
flutter_application_path = '../my_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'MyApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyApp
  
  #集成Flutter
 
   install_all_flutter_pods(flutter_application_path)
   
end

这个是pod里面的代码，需要改哪里么，🙏

**Comment by xieqi520** [comment]
可以了

**Comment by xieqi520** [comment]
我问一下这个是不是不支持安卓的java项目，那个push的回调参数在java里面好像没法写

**Comment by foxsofter** [comment]
肯定是可以的，不就是个闭包嘛，你自己找找怎么写
