### ISSUE TITLE
flutter main调用了两次

### ISSUE THREAD

**Issue by zxsr20** [flutter-thrio/thrio#127]
FlutterModule instance = FlutterModule.INSTANCE;
        ThrioModule.init(this, instance);

android的application中这样调用，就会导致flutter main函数执行两次

**Comment by foxsofter** [comment]
demo 并不会，你提供更多信息才有助于帮你查问题

**Comment by zxsr20** [comment]
把断点打在FlutterModule instance = FlutterModule.INSTANCE;这句话还没有执行下去就会执行一次main，然后执行下去又会执行两次main

**Comment by zxsr20** [comment]
engines[ep] = FlutterEngine(context, ep, readyListener)这句话只执行了一次

**Comment by zxsr20** [comment]
我把flutter端的main函数改成demo中main函数，还是会执行三次main，说明和dart代码没有关系

**Comment by zxsr20** [comment]
把初始化代码放到第一个页面去就只执行一次main函数，是否因为我们的application是有两个父类导致的？

**Comment by zxsr20** [comment]
找到原因了，是因为我的app是多进程的，所以导致其他进程多跑了几次main

**Comment by foxsofter** [comment]
> 找到原因了，是因为我的app是多进程的，所以导致其他进程多跑了几次main

这有点复杂了
