### ISSUE TITLE
v1插件的注册在打开第二个flutter页面的时候会出现'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference

### ISSUE THREAD

**Issue by zxsr20** [flutter-thrio/thrio#130]
v1插件的注册在打开第二个flutter页面的时候会出现'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference
在打开第一个flutter页面的时候不会

**Comment by zxsr20** [comment]
W/FlutterEnginePluginRegistry: Attempted to register plugin (com.tekartik.sqflite.SqflitePlugin@ff85ef0) but it was already registered with this FlutterEngine (io.flutter.embedding.engine.FlutterEngine@cc2e823).
W/FlutterEnginePluginRegistry: Attempted to register plugin (com.hellobike.flutter.thrio.ThrioPlugin@74dbc69) but it was already registered with this FlutterEngine (io.flutter.embedding.engine.FlutterEngine@cc2e823).
W/FlutterEnginePluginRegistry: Attempted to register plugin (io.flutter.plugins.urllauncher.UrlLauncherPlugin@db766ee) but it was already registered with this FlutterEngine (io.flutter.embedding.engine.FlutterEngine@cc2e823).
W/FlutterEnginePluginRegistry: Attempted to register plugin (io.flutter.plugins.videoplayer.VideoPlayerPlugin@287878f) but it was already registered with this FlutterEngine (io.flutter.embedding.engine.FlutterEngine@cc2e823).
W/FlutterEnginePluginRegistry: Attempted to register plugin (creativecreatorormaybenot.wakelock.WakelockPlugin@69c7a1c) but it was already registered with this FlutterEngine (io.flutter.embedding.engine.FlutterEngine@cc2e823).
W/FlutterEnginePluginRegistry: Attempted to register plugin (io.flutter.plugins.webviewflutter.WebViewFlutterPlugin@b7cb625) but it was already registered with this FlutterEngine (io.flutter.embedding.engine.FlutterEngine@cc2e823).
W/Activity: Slow Operation: Activity com.liveinstars.quhui/io.flutter.embedding.android.ThrioActivity onCreate took 99761ms
I/ActivityDelegate: onActivityStarted: 80165106
I/PageObservers: willAppear: url->/user/register index->1 params->test
I/ActivityDelegate: onActivityPreResumed: 80165106
I/PageObservers: didAppear: url->/user/register index->1 params->test
I/ActivityDelegate: onActivityResumed: 80165106
W/Looper: Slow Looper main: Long Msg: seq=357 plan=00:00:00.777  late=14ms wall=99882ms running=0ms h=android.app.ActivityThread$H w=159
W/Looper: Slow Looper main: Activity com.liveinstars.quhui/io.flutter.embedding.android.ThrioActivity is 99932ms late (wall=0ms running=0ms ClientTransaction{ callbacks=[android.app.servertransaction.TopResumedActivityChangeItem] }) because of 2 msg, msg 2 took 99882ms (seq=357 late=14ms h=android.app.ActivityThread$H w=159)
I/ActivityDelegate: onActivityStopped: 216915898
W/Looper: Slow Looper main: Activity com.liveinstars.quhui/com.blockmeta.bbs.overallserviceapplication.activity.login.LoginAccountActivity is 89976ms late (wall=32ms running=0ms ClientTransaction{ lifecycleRequest=android.app.servertransaction.StopActivityItem }) because of 6 msg, msg 1 took 99882ms (seq=357 late=14ms h=android.app.ActivityThread$H w=159)
I/flutter: PostPage-[Null#007db]
I/flutter: [D] flutterting1do builderFutureStatus.fulfilled
I/flutter: [D] flutterting1get myinterest from store
I/flutter: [D] flutterting postlistwidgetpage build
    SimplePullLoadWidget
D/SurfaceView: UPDATE null, mIsCastMode = false

**Comment by foxsofter** [comment]
#131 那个issue中第一个页面都挂了，你怎么打开的第二个页面了

**Comment by zxsr20** [comment]
就是报这个错
Slow Looper main: Activity com.liveinstars.quhui/io.flutter.embedding.android.ThrioActivity is 380ms late (wall=4ms running=0ms ClientTransaction{ callbacks=[android.app.servertransaction.TopResumedActivityChangeItem] }) because of 5 msg, msg 4 took 367ms (seq=317 late=17ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)
并且这个FlutterEngine@cc2e823也不是thrio创建的，系统不知道什么时候创建并绑定了，在打开第一个thrioactivity的时候没有出这个告警，应该是在后面创建的，我现在从flutter跳native再跳flutter就出现这个main looper卡住，页面不显示的问题了

**Comment by foxsofter** [comment]
你是不是自己继承了 FlutterActivity 之类的

**Comment by zxsr20** [comment]
哦，原来是没有flutter这边没有注册module

**Comment by zxsr20** [comment]
漏了一个module

**Comment by zxsr20** [comment]
但是这个W/FlutterEnginePluginRegistry: Attempted to register plugin (com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin@f296db4) but it was already registered with this FlutterEngine (io.flutter.embedding.engine还是在

**Comment by foxsofter** [comment]
这个影响啥了呢，可以不用管
