### ISSUE TITLE
从flutter页面跳到native页面，再打开一个flutter页面，第一个flutter页面会重新build，pageview会重置到index为0的位置，加了autokeepalive也没用

### ISSUE THREAD

**Issue by zxsr20** [flutter-thrio/thrio#132]
从flutter页面跳到native页面，再打开一个flutter页面，第一个flutter页面会重新build，pageview会重置到index为0的位置，加了autokeepalive也没用

**Comment by foxsofter** [comment]
https://github.com/flutter/flutter/issues/11655
https://stackoverflow.com/questions/52249578/how-to-deal-with-unwanted-widget-build

**Comment by zxsr20** [comment]
是第一个flutter会build两次，第一次pagecontroller中还保存着offset，第二次offset就为0了
