### ISSUE TITLE
NavigationController里面context只会赋值第一个Activity，导致泄露

### ISSUE THREAD

**Issue by taofaqi** [flutter-thrio/thrio#133]
override fun onActivityCreated(activity: Activity, savedInstanceState: Bundle?) {
        context = context ?: activity

        Remove.doRemove(activity)
        Push.doPush(activity)
    }
 ?: 操作符为空赋值，不为空不赋值，导致context只会赋值  启动的第一个Activity。

**Comment by foxsofter** [comment]
原来就是这样设计的，这也不涉及泄露，因为那个 context 在app 生命周期里面都不可能释放，实际的所有的Activity 都会被弱引用在 PageRouteHolder 上。

新版这里改了，不过最终不会泄露
