### ISSUE TITLE
thrio1.1.0版本引入到原生工程后影响原生导航显示

### ISSUE THREAD

**Issue by olderMonster** [flutter-thrio/thrio#134]
目前我们项目内是自定义导航控制器，但在部分页面会有导航随页面滚动显示或者隐藏的逻辑。还有部分页面是默认隐藏导航的逻辑。
1、目前出现问题的是页面内导航默认隐藏的页面。在引入thrio后这些页面内的导航会默认显示出来。当然可以通过设置thrio的导航隐藏类解决。但是我们有些功能是私有库，而thrio作为了framework是在整个工程内依赖的，也没有去单独在私有库中依赖，这样导致无法很方便的去解决该问题。
2、侧滑导致崩溃问题。我们的项目中没有用第三方的手势。
     崩溃问题我看了下，是找不到【handleNavigationTransition】方法，应该是内部交换方法替换掉原来的边缘滑动手势导致的。

请问能提供一个接口控制是否启用thrio的导航逻辑吗。
这样可以方便在项目内仅适用thrio的Flutter相关的功能，选择性使用导航相关的功能。

**Comment by foxsofter** [comment]
使用的哪个 pub 版本

**Comment by olderMonster** [comment]
> 使用的哪个 pub 版本

使用的1.1.0版本。
目前你这边的main分支应该是解决了导航的问题。目前我这边是直接依赖的你的main分支。
但是为了解决手势的问题我现在是本地修改源码的方式解决的。

**Comment by olderMonster** [comment]
![image](https://user-images.githubusercontent.com/9191869/102312095-fdcc1c80-3fa8-11eb-86cb-825f2a372fde.png)
![image](https://user-images.githubusercontent.com/9191869/102312116-091f4800-3fa9-11eb-8cf7-19324b7d27f5.png)
这是我本地为了项目正常所注释的代码部分，主要就是解决手势崩溃的问题

**Comment by foxsofter** [comment]
1.1.0 版本poppedResult存在bug，建议尽快升级到 1.3.2

**Comment by foxsofter** [comment]
你改的这些代码，Flutter手势应该就无效了吧，另外你的其它代码里面应该也用到了 handleNavigationTransition 吧

**Comment by olderMonster** [comment]
> 你改的这些代码，Flutter手势应该就无效了吧，另外你的其它代码里面应该也用到了 handleNavigationTransition 吧

嗯，是的，目前是禁用掉了手势，其实也和之前使用flutter_boost一致的，也是在fluttre页面不支持手势操作。handleNavigationTransition这个我在工程中还没发现在哪里有使用过。
好的，我这边会找时间升级thrio，看看是否已经可行了。

**Comment by foxsofter** [comment]
崩溃的堆栈能否贴出来

**Comment by foxsofter** [comment]
关于 handleNavigationTransition 冲突的问题没有太好的解决办法，先自行解决
