### ISSUE TITLE
Android原生页面跳转Flutter页面

### ISSUE THREAD

**Issue by xiaoqiang21** [flutter-thrio/thrio#135]
1. Android原生页面跳转Flutter页面闪屏加载2次
2. Flutter页面点击后退到原生页面是，第二次点击无法跳转，但log日志显示有数据
3. 如果是继承ThrioActivity第一次点击也是可以跳转，但第二次点击一直在fluter页面loading 
4. 如果是直接点击通过ThrioNavigator.push 跳转，第二次无响应

**Comment by foxsofter** [comment]
pub 1.3.3 已修复
