### ISSUE TITLE
iOS混编，随便进入Flutter页面，再进入原生来回多次闪退

### ISSUE THREAD

**Issue by zhou934381967** [flutter-thrio/thrio#136]
**Describe the bug**
iOS混编，随便进入Flutter页面，再进入原生来回多次闪退，随机点击多在app里面点点就会出现了

**To Reproduce**
1. 进入Flutter界面
2. 进入原生界面
3. 返回Flutter界面
4. 多操作几次，然后点点app其他界面

**Expected behavior**

**Flutter Doctor**
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.6 19G2021, locale zh-Hans-CN)
    • Flutter version 1.22.0 at /Users/zhoujianhui/Documents/flutter
    • Framework revision d408d302e2 (3 months ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/zhoujianhui/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • iPhone (2) (mobile)    • 7e865e3e587a45410df48d95485802cec608c942 • ios • iOS 14.1
    • iPhone 8 Plus (mobile) • E5685184-A6E0-476C-B025-8DFB3443F61D     • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)

! Doctor found issues in 1 category.

**OS & Device**
 - Device: [e.g. iPhoneXR]
 - OS: [e.g. iOS14.2]

**Error logs**
Add logs about the problem here.

**Comment by zhou934381967** [comment]
![截屏2020-12-17 下午3 50 54](https://user-images.githubusercontent.com/13718172/102463340-f169c180-4085-11eb-9e85-650e658a6d56.png)
io.flutter.10788830400.1.raster (17): EXC_BAD_ACCESS (code=1, address=0x0)

**Comment by foxsofter** [comment]
demo上暂时没能复现

**Comment by foxsofter** [comment]
如能提供可复现的demo，这个问题再 open
