### ISSUE TITLE
有考虑支持navigator2.0的page么?

### ISSUE THREAD

**Issue by lzhAndroid** [flutter-thrio/thrio#147]
感觉跟module的思路很像,处理的也是setting,还有动画这类的需求.

**Comment by foxsofter** [comment]
需要支持 Navigator 2.0 的什么东西，可否描述的更详细点 ~

**Comment by lzhAndroid** [comment]
你可以看一下CupertinoPage,Page这一套东西.如果Module能兼容page的话,可能长远看,移植会更方便些

**Comment by foxsofter** [comment]
你想说声明式路由？

**Comment by lzhAndroid** [comment]
恩,我们现在框架写的是声明式路由.如果能支持申明式路由肯定最好,不行的话,我觉得Moudlue可以增加类似ModluePage这样的结构,直接我传个Page进来,直接使用Page里面的name,还有它定义的转场动画,也能方便移植.不过ModluePage这种也可以自己去写.

**Comment by foxsofter** [comment]
集中将所有页面放到 pages 这种就不是太合理了

**Comment by lzhAndroid** [comment]
我看叶子节点的Module,不是就是一个Page对应一个Module么?还是我理解错了,可以多个Page在一个Module里面配置?

**Comment by foxsofter** [comment]
我说的是 Navigator 2.0

**Comment by lzhAndroid** [comment]
其实还好,你把pages当配置文件来看的话,这种设计其实没有什么问题.所有的配置集中管理,灵活性会更高一些,而且资源占用相对也还好

**Comment by foxsofter** [comment]
Navigator 2.0 并没有什么需要适配的，暂时不动了
