### ISSUE TITLE
Android移除两个Flutter之间的原生页面，然后push 某个flutter页面，push失败，且页面无法操作

### ISSUE THREAD

**Issue by Luozf12345** [flutter-thrio/thrio#152]
**Describe the bug**
flutter1->原生->flutter2这种场景，将中间的原生页面移除，然后从

**To Reproduce**
1. 用push打开页面，页面栈为：flutter1->原生->flutter2
2. remove（url，index）将原生页面移除
3. 按物理返回键从flutter2回到flutter1。此时，过程动画执行完毕，才能看到flutter2突然变成flutter1【异常1】
4. 在flutter1中点击push到某个flutter页面。此时，页面点击无法响应，且按返回键无发返回。【异常2】
5.从进入最近任务栏，再回到应用中。此时又可以操作。

**Expected behavior**
【异常1】flutter2随过场动画消失，直接看到下面的flutter1
【异常2】可以点击，正确跳转。

**Flutter Doctor**
Run the flutter doctor -v command and post the log.

**OS & Device**
 - Device: RedMi Note7 Pro
 - OS: MIUI 12.0.2
 - Version git最新old分支和main分支都存在该问题

**Error logs**
Add logs about the problem here.

**Comment by foxsofter** [comment]
不是太好解决，之前解决过这个问题在其它场景的情况，用的办法也只是取巧。本质上还需要修改引擎才能彻底解决，目前只能是想各种办法绕过，我已经试出来一个办法，不过体验不是太好，暂时先不发布了。

**Comment by foxsofter** [comment]
1.7.5 已发布一个fix，这种场景如不能避免至少是可用的，另外有其它方案可以解决，对流程改动比目前这种方案大，暂时没时间测试

**Comment by foxsofter** [comment]
1.7.7彻底解决了
