### ISSUE TITLE
Android上Flutter页面回收重启问题

### ISSUE THREAD

**Issue by shingohu** [flutter-thrio/thrio#157]
**Describe the bug**
Android上由于Activity在后台时候会被系统回收,下次打开时会重启原有界面,非Flutter页面没有问题,
但是在Flutter页面的时候回收重启时,原有的页面路由不会恢复,出现了NavigatorMeterialApp中设置的home界面

**To Reproduce**
1.打开demo->push flutter1
2.退到后台,操作其它app一段时间(具体看系统内存,垃圾手机比较容易出现)
3.再次点开demo

期望结果:回收重启后Flutter路由可以还原

**Comment by foxsofter** [comment]
已修复，pub 1.8.0 试试看

**Comment by foxsofter** [comment]
这个问题是，开发者设置中开启：不保留后台进程，保留Activity 两个选项后可复现，现象是进程资源已经被释放了，但 Activity 在下次启动时被恢复了，但进程的资源并不存在，导致停留在加载页
