### ISSUE TITLE
继承ThrioActivity之后，flutter与android原生之间如何通信？

### ISSUE THREAD

**Issue by Aronlong1001** [flutter-thrio/thrio#162]
继承ThrioActivity之后，flutter与android原生之间如何通信？

methodChannel = ThrioChannel(intent.getEntrypoint(), CHANNEL)
methodChannel.setupMethodChannel(flutterEngine.dartExecutor)

没有回调怎么写逻辑？

**Comment by foxsofter** [comment]
registryMethod

**Comment by Aronlong1001** [comment]
> registryMethod

methodChannel.registryMethod("callNative", object : MethodHandler{
            override fun invoke(p1: Map<String, Any?>?, p2: NullableAnyCallback) {

            }
        })

是这样用吗？那在回调里面如何使用result.success呢？
