### ISSUE TITLE
1.7.2 版本 从flutter页面跳native页面再跳flutter页面，前一个flutter页面会didChangeDependencies两次，第二次的时候pageview的controller中的offset被清空

### ISSUE THREAD

**Issue by zxsr20** [flutter-thrio/thrio#163]
1.7.2 版本 从flutter页面跳native页面再跳flutter页面，前一个flutter页面会didChangeDependencies两次，第一次没有问题，第二次的时候pageview的controller中的offset被清空，导致pageview又回到第一个页面，请问是怎么回事，flutter页面之前跳，都不会触发didChangeDependencies

**Comment by foxsofter** [comment]
1.7.11是最新版，尽快升级吧，这个版本上未发现你说的这个问题，老版本我就不验证了
