### ISSUE TITLE
如何在flutter端发送通知，让flutteractivity能打开友盟分享的dialog，想重写onNotify方法是私有的，或者在外部能不能通过ThrioNavigator获得当前的activity实例？

### ISSUE THREAD

**Issue by zxsr20** [flutter-thrio/thrio#165]
想要实现flutte端点击按钮，在native端打开友盟分享的dialog，想继承thrioactivity重写onNotify方法是私有的不行，在外部通过自己发channel message获取不到当前的activity，能否通过ThrioNavigator获得当前的activity实例？求教

**Comment by foxsofter** [comment]
你要的方式可能不是你想要的，你要分享的内容是 Flutter 的？

**Comment by zxsr20** [comment]
要分享的是flutter http获取的内容

**Comment by foxsofter** [comment]
分享网址？
