### ISSUE TITLE
安卓期望开放FlutterEngineFactory

### ISSUE THREAD

**Issue by neeboo** [flutter-thrio/thrio#25]
因为需要加入自定义的引擎，希望可以用这个object以获得当前的cache_engine，做到复用

**Comment by foxsofter** [comment]
自定义引擎的场景是什么？我们可能不会开放引擎给使用者，后续Android上我们还是会加上多引擎模式，单引擎和多引擎对使用者应该是无感的。

**Comment by neeboo** [comment]
> 自定义引擎的场景是什么？我们可能不会开放引擎给使用者，后续Android上我们还是会加上多引擎模式，单引擎和多引擎对使用者应该是无感的。

不好意思，我的issue有问题，是需要自己加入methodChannel和一些其他的channel

**Comment by foxsofter** [comment]
> > 自定义引擎的场景是什么？我们可能不会开放引擎给使用者，后续Android上我们还是会加上多引擎模式，单引擎和多引擎对使用者应该是无感的。
> 
> 不好意思，我的issue有问题，是需要自己加入methodChannel和一些其他的channel

你自定义插件就好了，channel的用法没有任何改变，只是 thrio 会帮你注册插件，多引擎的时候也会，所以什么都不需要改变的。

**Comment by neeboo** [comment]
> > > 自定义引擎的场景是什么？我们可能不会开放引擎给使用者，后续Android上我们还是会加上多引擎模式，单引擎和多引擎对使用者应该是无感的。
> > 
> > 
> > 不好意思，我的issue有问题，是需要自己加入methodChannel和一些其他的channel
> 
> 你自定义插件就好了，channel的用法没有任何改变，只是 thrio 会帮你注册插件，多引擎的时候也会，所以什么都不需要改变的。

OK
