### ISSUE TITLE
flutter端 url 带点的问题 "."

### ISSUE THREAD

**Issue by prczhb** [flutter-thrio/thrio#27]
![image](https://user-images.githubusercontent.com/26354648/81183427-bd073080-8fe1-11ea-8c0a-63a403a08d79.png)

我自己的url里面带"." 正好thrio里关于url的解析也带"." 这就导致了url错误的问题.
建议调整一下获取原始url方法

**Comment by foxsofter** [comment]
这就有点尴尬了，要改一改

**Comment by foxsofter** [comment]
在0.1.6修复
