### ISSUE TITLE
Android端 minSdkVersion 为 21 (Android 5.0),是不是有点高了

### ISSUE THREAD

**Issue by prczhb** [flutter-thrio/thrio#28]
![image](https://user-images.githubusercontent.com/26354648/81184472-07d57800-8fe3-11ea-8527-c8f89fb9c971.png)

希望能调低一点 minSdkVersion ,尽量兼容旧系统吧
😁😁😁😁😁😁

**Comment by foxsofter** [comment]
5.0以下也太老了吧，你什么场景下还用到

**Comment by prczhb** [comment]
![image](https://user-images.githubusercontent.com/26354648/81473820-e4553c00-9233-11ea-849e-ba66785ce9f1.png)
[https://developer.android.google.cn/about/dashboards/](https://developer.android.google.cn/about/dashboards/)
[https://developer.android.com/about/dashboards](https://developer.android.com/about/dashboards)
按照目前的Android系统分布,4,4(19)的还将近7%的占有率,也是有很多啊, 倒是4.4以下的可以忽略不计了.

**Comment by foxsofter** [comment]
你可以自己试试，没问题提 PR

**Comment by prczhb** [comment]
> 你可以自己试试，没问题提 PR

已提交pr
