### ISSUE TITLE
Android 端 返回键的问题(iOS的效果不知道)

### ISSUE THREAD

**Issue by prczhb** [flutter-thrio/thrio#29]
![image](https://user-images.githubusercontent.com/26354648/81265948-82030c80-9076-11ea-9a86-5225a6552e04.png)

官方的flutteractivity里, 按返回键(手机的物理按键) 它会先弹出flutter 的堆栈里的页面(触发 dart: Navigator.of(context).pop();) ,当无页面可弹时 他才会关闭当前activity (触发 dart: SystemNavigator.pop();)
例如: 入栈:A(原生) -> B1(flutter) -> B2(flutter)  -> B3(flutter)    (B1 到 B2 B3 是通过 Navigator.of(context).push()来跳转的 而非其他方式)
按返回键  B3(flutter) -> B2(flutter) -> B1(flutter) -> A(原生)

而 thrio ,按返回键时(手机的物理按键) ,他不会弹出flutter 的堆栈里的页面 而是直接关闭当前activity .
例如: 入栈:A(原生) -> B1(flutter) -> B2(flutter)  -> B3(flutter)    (B1 到 B2 B3 是通过 Navigator.of(context).push()来跳转的, 而非 Thrio 的方式)
按返回键  B3(flutter) -> A(原生)  (直接关闭了整个flutter)

请问这种情况该咋处理? 我需要通过 Thrio 的页面打开方式 ,而不能用flutter的 Navigator.of(context)方式?

**Comment by foxsofter** [comment]
thrio 默认要求 Flutter使用 ThrioNavigator 来打开页面哦，你这种方式无法同步栈结构

**Comment by foxsofter** [comment]
如果你使用内置的Navigator进行push，一样需要用Navigator的pop来关闭，我试下来是可以的，如果没必要建议你都要用ThrioNavigator，内置的Navigator可以用来做弹窗的场景。
但使用内置的Navigator，你需要自己拦截返回键做处理，具体的拦截方式，文档上有，WillPopScope这个 Widget。

**Comment by prczhb** [comment]
> 如果你使用内置的Navigator进行push，一样需要用Navigator的pop来关闭，我试下来是可以的，如果没必要建议你都要用ThrioNavigator，内置的Navigator可以用来做弹窗的场景。
> 但使用内置的Navigator，你需要自己拦截返回键做处理，具体的拦截方式，文档上有，WillPopScope这个 Widget。

好的 谢谢 我这里统一一下
