### ISSUE TITLE
popTo可否支持数据传递params

### ISSUE THREAD

**Issue by banwenmang** [flutter-thrio/thrio#37]
1. FlutterViewController中从栈底至栈顶依次为页面A -> 页面B -> 页面C。
2. 现在使用popTo 至页面A。
3. 如何从页面C，通过popTo携带参数至页面A

**Comment by foxsofter** [comment]
不能支持，popParams只能给到push，原理上就行不通，你的需求只需要用 notify 就可以实现

**Comment by banwenmang** [comment]
OK
