### ISSUE TITLE
高版本Xcode创建的iOS工程，以flutter_module方式引入插件，获取 navigationController 可能为空

### ISSUE THREAD

**Issue by renshaojuncool** [flutter-thrio/thrio#42]
高版本Xcode创建的工程，因为```SceneDelegate```缘故
``` UIApplication+Thrio.m ```  , ``` topmostNavigationController  ```方法中，
``` UIViewController *topmostViewController = self.delegate.window.rootViewController; ```获取可能为nil

**Comment by foxsofter** [comment]
iOS 13呢。。。我应该可以兼容SceneDelegate，需不需要的问题，你项目上应该没用到吧

**Comment by renshaojuncool** [comment]
> iOS 13呢。。。我应该可以兼容SceneDelegate，需不需要的问题，你项目上应该没用到吧

demo中，iOS13模拟器跑起来没问题。我们项目是Xcode11.5 创建的，建立后包含 SceneDelegate，这样跑起来，会一直取到nil，就暂时放弃，使用flutter_boost。

**Comment by foxsofter** [comment]
API_AVAILABLE(ios(13.0)) @protocol UIWindowSceneDelegate <UISceneDelegate>
你的项目只支持iOS 13.0以上嘛

**Comment by renshaojuncool** [comment]
> API_AVAILABLE(ios(13.0)) @protocol UIWindowSceneDelegate
> 你的项目只支持iOS 13.0以上嘛

iOS13以下，window在 Appdelegate里面可以取到的，和iOS13以上，在 SceneDelegate 才可以取到，和我是否只支持iOS13没有关系吧

**Comment by foxsofter** [comment]
你进下QQ群聊吧 1014085473

**Comment by foxsofter** [comment]
SceneDelegate在目前看来大部分App上并不会用到，分屏模式还早，且跟AppDelegate几乎无差别，thrio不打算支持。
