### ISSUE TITLE
请问我应该怎么注册自己的 Method Channel 呢

### ISSUE THREAD

**Issue by sunimp** [flutter-thrio/thrio#47]
请问 iOS 应该怎么注册自己的 Method Channel 呢

`ThrioChannel` 暴露了方法：
`- (void)setupMethodChannel:(NSObject<FlutterBinaryMessenger> *)messenger`

`messenger`参数应该怎么传呢

**Comment by foxsofter** [comment]
FlutterEngine上有，最好的方式还是像原来一样放在 plugin 的 registerWithRegistrar 方法中

**Comment by foxsofter** [comment]
自定义channel，依然可以像原来一样玩，不需要使用ThrioChannel

**Comment by foxsofter** [comment]
在你自己的plugin里面

**Comment by sunimp** [comment]
> FlutterEngine上有

我刚看到可以通过：
```objc
[ThrioModule init:self];
FlutterEngine *engine = [ThrioNavigator getEngineByEntrypoint:@""];
```
这样来拿到引擎，不过我没有尝试自己创建一个引擎，然后用 `FlutterMethodChannel` 去注册，我接下来试试，感谢

**Comment by sunimp** [comment]
> FlutterEngine上有，最好的方式还是像原来一样放在 plugin 的 registerWithRegistrar 方法中

我刚尝试了拿到 `thrio` 创建的 flutter 引擎:
```objc
FlutterEngine *engine = [ThrioNavigator getEngineByEntrypoint:@""];
```
尝试调用下边的方法让 `ThrioChannel`的`_methodHandlers`就绪
```objc 
[channel setupMethodChannel:engine.messenger];
```
但这个 channel 似乎并未生效，我在`thrio`里断点追踪调试一下看看问题在哪里

**Comment by sunimp** [comment]
> FlutterEngine上有，最好的方式还是像原来一样放在 plugin 的 registerWithRegistrar 方法中

找到了！
`ThrioChannel` 里对 `methodName` 搞了个前缀 `_method_`...
🤣

**Comment by sunimp** [comment]
使用原本的 `FlutterMethodChannel` 注册是可以的，我的问题解决了，感谢，我关闭了这个 issue。
