### ISSUE TITLE
[iOS] 如何自定义 NavigatorFlutterViewController ?

### ISSUE THREAD

**Issue by sunimp** [flutter-thrio/thrio#48]
我通过继承 `NavigatorFlutterViewController`
```objc
NavigatorFlutterPageBuilder pageBuilder = ^NavigatorFlutterViewController* {
     return [[CustomFlutterViewController alloc] initWithEntrypoint:@""];
};
[self setFlutterPageBuilder: pageBuilder];
```

进入 Flutter 页面是白屏，请问正确的自定义方式是什么？

**Comment by sunimp** [comment]
白屏的原因找到了，是因为我在自定义的控制器里重写了 `surfaceUpdated:` 而没有调用 super 实现
```objective-c
- (void)surfaceUpdated:(BOOL)appeared {
    if (appeared) {
        [self setNeedsStatusBarAppearanceUpdate];
    }
}
```
注释掉就可以了，我看到 `thrio` 定义、调用了，但似乎并没有使用到 `update` 参数，猜测这方法应该是 `FlutterViewController` 内部方法，不过我没有用运行时证实。

不过我又发现了新的问题，在我尝试在 flutter 页面 push 到原生，再从原生 pop 到 flutter 时，导航栏会出现黑色的，并且这时 flutter 页面还会跳动，Example 则是没有这个问题的，很大可能和我使用了 `QMUIKit` 有关。
说到 `QMUIKit`，还有个问题，`thrio` 在隐藏导航栏处理边缘返回手势的时候 hook 了 `UINavigationController`属性和方法: 
```objective-c
...
id  target = self.interactivePopGestureRecognizer.delegate
SEL action = NSSelectorFromString(@"handleNavigationTransition:");
...
```
为原本因隐藏导航消失的边缘返回手势，添加一个新的边缘手势，这里获取了系统的 delegate ，让这个 delegate handle 这个 Transition 的手势，这里原本是没问题的，但 `QMUIKit` 也 hook 了这个 delegate，并且已经把它修改掉了，提供一个属性供访问原本的 delegate，于是在 `thrio` 获取 `self.interactivePopGestureRecognizer.delegate` 时会报错。

我目前暂时是通过获取 `qmui_interactivePopGestureRecognizerDelegate` 的方式解决的冲突。

目前问题有点儿多，flutter 只是我作为 module 嵌入到原生项目，只是涉及了10几个页面，但遇到的问题太多了，考虑换掉。

**Comment by foxsofter** [comment]
哈哈哈，你这还没入坑就已经要弃坑了嘛，另外你后面这个问题应该要 QMUI 自己解决吧，改掉 delegate 的方式不合理，可参照 thrio 中的处理方式，虽然吃掉了，但还是要吐出来

**Comment by sunimp** [comment]
> 哈哈哈，你这还没入坑就已经要弃坑了嘛，另外你后面这个问题应该要 QMUI 自己解决吧，改掉 delegate 的方式不合理，可参照 thrio 中的处理方式，虽然吃掉了，但还是要吐出来

入坑了有段时间了，之前使用的 flutter 版本比较低(`v1.7.8`)有太多问题，内存泄漏、打包问题，`xcode_backend.sh` 脚本里对 `App.framework` 权限修改的问题，安卓打aar包的问题....等等。

版本落后了太多，导致很多新特性(Metal等)享受不到，很多 flutter 的依赖库，尤其是 `thrio` 用不了，于是直接从 `1.7.8` 升到了 `1.17.3`，跨度有点儿大了，花了一天多时间终于把这些接入问题修改好了，但是，遇到了和 `QMUIKit`的兼容性问题，这个确实是 qmui 的问题，它吃进去倒也吐出来了，但吐出来的不是原样儿的，目前找到问题点，我自己琢磨琢磨怎么解决比较好。

我把 issue 关了。
