### ISSUE TITLE
Flutter内通过ThrioNavigator push时参数不支持自定义对象

### ISSUE THREAD

**Issue by sunimp** [flutter-thrio/thrio#49]
比如：
```objc
List<Friend> friends = .....
ThrioNavigator.push(url:"example1", params: friends.first)
```
会报 Friend 未定义异常，我查看了一下Thrio 的逻辑，大概是因为 Thrio 总是会去调用原生的部分，文档里有提到`优先打开原生页面，原生打不开才会尝试打开Flutter页面`，而这个flutter的自定义类在原生下肯定是 undefined 的

不知道这种情况是已知问题还是未曾发现.

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by foxsofter** [comment]
设计如此，路由尽量不要传入复杂类型，channel支持的类型都可以传，暂时没有支持复杂类型的计划，如果你自己要做，可以用json类做序列化反序列化

**Comment by sunimp** [comment]
了解，我目前也是这样（序列化/反序列化）解决的。
