### ISSUE TITLE
大佬，这个是错误是怎么导致的，排查了快一天了。

### ISSUE THREAD

**Issue by SuPeiSen** [flutter-thrio/thrio#52]
`2020-07-04 18:33:43.797706+0800 ios_app[30473:294343] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFBoolean compare:]: nil argument'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23e3cf0e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50ba89b2 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23ecfa51 _CFThrowFormattedException + 194
	3   CoreFoundation                      0x00007fff23ecfec9 -[__NSCFBoolean compare:].cold.1 + 41
	4   CoreFoundation                      0x00007fff23d7399b -[__NSCFBoolean compare:] + 475
	5   CoreFoundation                      0x00007fff23d731d6 -[__NSCFBoolean isEqualToNumber:] + 22
	6   thrio                               0x0000000110326da2 -[UINavigationController(Navigator) thrio_pushViewController:animated:] + 178
	7   thrio                               0x0000000110329b6c __117-[UINavigationController(Navigator) thrio_pushViewController:url:params:animated:fromEntrypoint:result:poppedResult:]_block_invoke + 172
	8   thrio                               0x000000011032b395 __102-[UIViewController(Navigator) thrio_pushUrl:index:params:animated:fromEntrypoint:result:poppedResult:]_block_invoke + 165
	9   Flutter                             0x000000010e14c357 _ZNSt3__110__function6__funcIN3fml8internal14CopyableLambdaIZN7flutter29PlatformMessageResponseDarwin8CompleteENS_10unique_ptrINS2_7MappingENS_14default_deleteIS8_EEEEE3$_0EENS_9allocatorISD_EEFvvEEclEv + 51
	10  Flutter                             0x000000010e161267 _ZN3fml15MessageLoopImpl10FlushTasksENS_9FlushTypeE + 117
	11  Flutter                             0x000000010e1661b4 _ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 26
	12  CoreFoundation                      0x00007fff23da14b4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	13  CoreFoundation                      0x00007fff23da114e __CFRunLoopDoTimer + 1038
	14  CoreFoundation                      0x00007fff23da07aa __CFRunLoopDoTimers + 282
	15  CoreFoundation                      0x00007fff23d9b3fe __CFRunLoopRun + 1950
	16  CoreFoundation                      0x00007fff23d9a944 CFRunLoopRunSpecific + 404
	17  GraphicsServices                    0x00007fff38ba6c1a GSEventRunModal + 139
	18  UIKitCore                           0x00007fff48c8b9ec UIApplicationMain + 1605
	19  ios_app                             0x000000010deb4a62 main + 114
	20  libdyld.dylib                       0x00007fff51a231fd start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) `

**Comment by foxsofter** [comment]
能否补充下上下文，或者给个demo
