### ISSUE TITLE
适配1.20.x

### ISSUE THREAD

**Issue by foxsofter** [flutter-thrio/thrio#64]
#62

**Comment by prczhb** [comment]
![image](https://user-images.githubusercontent.com/26354648/91677757-4258b700-eb76-11ea-9c17-9d0f3d62d59a.png)

flutter 1.20.2 android编译报错

**Comment by foxsofter** [comment]
没适配呢，所以还不能用哦 ~_~

**Comment by foxsofter** [comment]
1.20.x短期内还不打算适配，等更多小版本稳定之后再看看，Android的改动比较大

**Comment by foxsofter** [comment]
已适配，可以用 master 分支尝鲜
