### ISSUE TITLE
No implementation found for method push on channel _method___thrio_app__

### ISSUE THREAD

**Issue by you-zuo** [flutter-thrio/thrio#65]
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method push on channel _method___thrio_app__)
E/flutter ( 8687): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter ( 8687): <asynchronous suspension>
E/flutter ( 8687): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter ( 8687): #2      ThrioChannel.invokeMethod (package:thrio/src/channel/thrio_channel.dart:63:27)
E/flutter ( 8687): #3      NavigatorRouteSendChannel.push (package:thrio/src/navigator/navigator_route_send_channel.dart:41:21)
E/flutter ( 8687): #4      ThrioNavigatorImplement.push (package:thrio/src/navigator/thrio_navigator_implement.dart:123:10)
E/flutter ( 8687): #5      ThrioNavigator.push (package:thrio/src/navigator/thrio_navigator.dart:42:31)
E/flutter ( 8687): #6      MyPage._settingList.<anonymous closure> (package:time_bourse/page/my/my_page.dart:305:41)
E/flutter ( 8687): #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
E/flutter ( 8687): #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
E/flutter ( 8687): #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 8687): #10     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
E/flutter ( 8687): #11     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
E/flutter ( 8687): #12     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:254:7)
E/flutter ( 8687): #13     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter ( 8687): #14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter ( 8687): #15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter ( 8687): #16     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 8687): #17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 8687): #18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 8687): #19     _rootRunUnary (dart:async/zone.dart:1196:13)
E/flutter ( 8687): #20     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter ( 8687): #21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter ( 8687): #22     _invoke1 (dart:ui/hooks.dart:275:10)
E/flutter ( 8687): #23     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)

请问下flutter作为第一屏 flutter—>native1 报这个错是什么原因

**Comment by foxsofter** [comment]
并没有设计可以使用flutter使用在第一屏，当然可以通过一些办法来做到，你是怎么做的

**Comment by you-zuo** [comment]
照着demo引用的，项目里有个原生界面的插件，需要从原生界面跳转Flutter页面，ios测试可用，Android第一次的时候跳转失败

**Comment by foxsofter** [comment]
flutter doctor -v 的信息给下，可以直接加ＱＱ群聊

**Comment by you-zuo** [comment]
[✓] Flutter (Channel unknown, v1.17.1, on Mac OS X 10.15.6 19G2021, locale zh-Hans-CN)
    • Flutter version 1.17.1 at /Users/youzuo/fvm/versions/1.17.1
    • Framework revision f7a6a7906b (3 months ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/youzuo/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (4 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • macOS                     • macOS         • darwin-x64     • Mac OS X 10.15.6 19G2021
    • Chrome                    • chrome        • web-javascript • Google Chrome 84.0.4147.125
    • Web Server                • web-server    • web-javascript • Flutter Tools

已加群
