### ISSUE TITLE
建议 Android 中自定义FlutterView等的代码切换成java的是否会更好

### ISSUE THREAD

**Issue by prczhb** [flutter-thrio/thrio#67]
![image](https://user-images.githubusercontent.com/26354648/91849739-17ae5180-ec8f-11ea-920b-c6b3a6454363.png)

![image](https://user-images.githubusercontent.com/26354648/91850044-87244100-ec8f-11ea-9ecb-c06c82e60867.png)

现在自定义的flutteractivity 是使用的kotlin编写的, 但他的源码FlutterActivity等是java编写的. 并且flutter又是频繁更新, 如果把自定义的flutter的编译语言切换回java, 在官方更新了FlutterActivity等相关代码时, 通过对比等能更方便去更新自定义的Activity等代码.

**Comment by foxsofter** [comment]
语言无所谓，只是不想维护两份不一样的语言的代码，原来的想法是以后分道扬镳，或者官方的代码没有问题了可以考虑切回去 ~_~

**Comment by foxsofter** [comment]
我确实又切换成Java代码了，主要是方便阅读源码的人对比，我到底改了啥
