### ISSUE TITLE
内存泄露严重

### ISSUE THREAD

**Issue by wendeqiang** [flutter-thrio/thrio#69]
我在Appdelegate中 执行[ThrioModule init:[RootThrioModule new]]; 代码之后，App一启动，内存就在不断增加。flutter版本是stable 1.75.5,希望给出解答

**Comment by foxsofter** [comment]
demo能否提供下，或者你看看 thrio 的 demo 有没有这个问题

**Comment by foxsofter** [comment]
你Flutter版本是不是发错了， @wendeqiang

**Comment by wendeqiang** [comment]
没有呀，1.17.5




            
            
                
                    
                            
                                
                            
                            
                                2227810098
                            
                    
                        
                            
                                    邮箱：2227810098@qq.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


在2020年09月04日 11:12，foxsofter 写道： 
你Flutter版本是不是发错了， @wendeqiang

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/hellobike/flutter_thrio/issues/69#issuecomment-686874914",
"url": "https://github.com/hellobike/flutter_thrio/issues/69#issuecomment-686874914",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by foxsofter** [comment]
你说的内存泄漏，具体是指什么现象，描述清楚步骤，贴上一张内存占用图就更好了，不然没办法判断了，我在1.17.5下面跑了下thrio 的 demo 重复打开关闭 Flutter 页面内存占用还是比较稳定的

**Comment by wendeqiang** [comment]
我这边自己再排查一下，看看是不是使用方法不对。
