### ISSUE TITLE
真机运行正常，模拟器运行报错

### ISSUE THREAD

**Issue by wendeqiang** [flutter-thrio/thrio#70]
<img width="1363" alt="截屏2020-09-04 下午6 56 13" src="https://user-images.githubusercontent.com/15044864/92232066-70c0f400-eee0-11ea-8b17-47ac22c75086.png">

**Comment by foxsofter** [comment]
真机跟模拟器切换的时候，要重新生成下

**Comment by wendeqiang** [comment]
我是把这个组件化到我们项目的，这个怎么重新生成呢




            
            
                
                    
                            
                                
                            
                            
                                2227810098
                            
                    
                        
                            
                                    邮箱：2227810098@qq.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


在2020年09月04日 19:38，foxsofter 写道： 
真机跟模拟器切换的时候，要重新生成下

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/hellobike/flutter_thrio/issues/70#issuecomment-687090848",
"url": "https://github.com/hellobike/flutter_thrio/issues/70#issuecomment-687090848",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by wendeqiang** [comment]
我是将flutter部分及其依赖库打包成framework然后组件化集成到我们项目中的，然后就会出现这个错误，真机正常的。




            
            
                
                    
                            
                                
                            
                            
                                2227810098
                            
                    
                        
                            
                                    邮箱：2227810098@qq.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


在2020年09月04日 19:51，wendeqiang 写道： 
我是把这个组件化到我们项目的，这个怎么重新生成呢




            
            
                
                    
                            
                                
                            
                            
                                2227810098
                            
                    
                        
                            
                                    邮箱：2227810098@qq.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


在2020年09月04日 19:38，foxsofter 写道： 
真机跟模拟器切换的时候，要重新生成下

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/hellobike/flutter_thrio/issues/70#issuecomment-687090848",
"url": "https://github.com/hellobike/flutter_thrio/issues/70#issuecomment-687090848",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by foxsofter** [comment]
Google下
