### ISSUE TITLE
stable 1.17.5下执行你的示例工程pod install 报错，查看了该版本下，没有这个podhelper文件

### ISSUE THREAD

**Issue by wendeqiang** [flutter-thrio/thrio#71]
<img width="971" alt="截屏2020-09-11 下午3 42 44" src="https://user-images.githubusercontent.com/15044864/92885875-c009a600-f445-11ea-8bb6-1cb63b2e713c.png">

**Comment by foxsofter** [comment]
$ rm ios/Podfile
$ flutter build ios

**Comment by wendeqiang** [comment]
好的，完美的解决了我的问题，谢谢
