### ISSUE TITLE
Android 是否支持放入 ViewPager 中？

### ISSUE THREAD

**Issue by wangzhen90** [flutter-thrio/thrio#76]
因为要考虑放入首页 Activity 的 ViewPager 中，请问框架是否支持一个 ViewPager 中有多个 Flutter 页面存在的场景？
目前看源码只是支持了 Activity。

**Comment by foxsofter** [comment]
Fragment不考虑支持，可能导致维护成本过高，你这种场景建议还是用原生来实现吧，并不是全部用Flutter更好，不能提效的时候原生其实是更好的选择

**Comment by wangzhen90** [comment]
> Fragment不考虑支持，可能导致维护成本过高，你这种场景建议还是用原生来实现吧，并不是全部用Flutter更好，不能提效的时候原生其实是更好的选择

维护成本指的是哪方面的？Router 的维护吗？主要考虑的是日常工作大部分都在改首页，如果支持了 Fragment 能带来广阔的应用场景，如果只支持二级页应用场景就要少的多了。

**Comment by wangzhen90** [comment]
@foxsofter 我理解的是无论是 Activity 还是 Fragment，都是一个 FlutterView，在 push / pop 的时候判断当前的页面是 native 还是 Flutter 的，然后做不同的处理，不知道真实做起来的时候复杂度会怎么样？

**Comment by foxsofter** [comment]
如果你要这样用，可以考虑直接整个首页是 Flutter，这种方式是支持的，从我个人的角度，我可能会倾向于只保留一种页面的构建方式，要么是 Activity 要么是 Fragment，但是只用 Fragment 来构建页面的场景应该不存在，所以我只保留了 Activity，无所谓好与不好吧，仅仅是为了简化

**Comment by KevinGong2013** [comment]
> @foxsofter 我理解的是无论是 Activity 还是 Fragment，都是一个 FlutterView，在 push / pop 的时候判断当前的页面是 native 还是 Flutter 的，然后做不同的处理，不知道真实做起来的时候复杂度会怎么样？

试一下[faraday](https://github.com/gfaraday/g_faraday)应该可以满足你的需求。
