### ISSUE TITLE
iOS 怎么获取到当前的flutterEngine，有公开的单例吗

### ISSUE THREAD

**Issue by wendeqiang** [flutter-thrio/thrio#80]

**Comment by fourdimspace** [comment]
可以获取的
IOS：
ThrioModule.`init`(FlutterMainModule())
 let engine = ThrioNavigator.getEngineByEntrypoint(AppDelegate.kDefaultEngineName)

Android：
ThrioModule.init(this, FlutterModule)
val flutterEngine = FlutterEngineCache.getInstance().get( kThrioEngineFlutterId)

**Comment by wendeqiang** [comment]
好的，完美解决我的问题。因为项目安卓使用通知功能有问题，只能通过系统FlutterMethodChannel进行消息传递，所以需要engine

**Comment by foxsofter** [comment]
插件注册方式不会受影响吧，为什么需要Engine
