### ISSUE TITLE
[IOS] UIImagePickerViewController 拍照的delegate被替换了

### ISSUE THREAD

**Issue by fourdimspace** [flutter-thrio/thrio#81]
UINavigationController+PopGesture.m中

- (void)thrio_addPopGesture {
		if (![self.interactivePopGestureRecognizer.view.gestureRecognizers containsObject:self.thrio_popGestureRecognizer]) {
			[self.interactivePopGestureRecognizer.view 				addGestureRecognizer:self.thrio_popGestureRecognizer];
	}
		self.delegate = self.thrio_navigationControllerDelegate;   //这句把UIImagePickerViewController的delegate替换了
		self.interactivePopGestureRecognizer.enabled = NO;
	}

**Comment by foxsofter** [comment]
问题是什么呢

**Comment by fourdimspace** [comment]
> 问题是什么呢
self.delegate = self.thrio_navigationControllerDelegate; //
这句把UIImagePickerViewController的delegate替换了, 因为UIImagePickerViewController是一个UINavigationController，所以代码会执行上述代码，会把UIImagePickerViewController的delegate设置为self.thrio_navigationControllerDelegate，用户自己设置的delegate就无效了，造成拍摄的图片无法通过delegate返回

**Comment by foxsofter** [comment]
这个问题解决过了，你看看新版
