### ISSUE TITLE
在swift中使用registerPageBuilder注册一个跳转路由，想要在flutter页面跳转到原生页面，一直失败，无法完成跳转。

### ISSUE THREAD

**Issue by wendeqiang** [flutter-thrio/thrio#87]
///注册跳转路由
    override func onPageRegister() {
        self.registerPageBuilder({ param -> UIViewController? in
            return MineSharePageController()
        }, forUrl: "native1")()
        self.registerPageObserver(self)()
    }
无法跳转到相应页面

**Comment by foxsofter** [comment]
你的意思是，你在原生可以通过 url 跳转到这个页面嘛？

**Comment by wendeqiang** [comment]
找到问题了，在swift项目里注册这个通知必须用oc文件才行，可能是因为你这个registerpage方法利用的是runtime的关系，原生跳转到flutter是可以的

**Comment by foxsofter** [comment]
我后面会试试 Swift，这个跟运行时可能是没关系的

**Comment by foxsofter** [comment]
main分支上有示例，可以打开 Swift 页面 @wendeqiang

**Comment by wendeqiang** [comment]
好的，我稍后看看，谢谢了
