### ISSUE TITLE
接入主项目，存在相关问题

### ISSUE THREAD

**Issue by zeqinjie** [flutter-thrio/thrio#89]
存在问题 😢

1. 由于 Flutter 打开原生 APP 是需要返回 ViewController，不便于结合项目已有的路由（**需要重新注册一套路由，不便于原有路由统一，需要管理两套）**
2. 通知是基于 ViewController 来实现协议的方法，不便于统一操作 **（不能在非控制器页面去获取通知数据）**
3. 必须基于 ThrioNavigator 注册管理的路由页面，才能接收通知的数据
4. 接收消息回调时机是在上个页面销毁，当前页面 viewDidAppear 出现时候
5. 参数不支持自定义对象类型
6. 在混合开发中出现 crash 问题

**Comment by foxsofter** [comment]
1. 目前确实是这样，如果是新项目，可以考虑直接都采用 thrio 来管理路由，如果是老项目，重新注册需要在 Flutter 侧打开的原生页面就可以了
2. 通知是页面通知，在跨平台的层面，页面才是可以统一抽象的自治单元，所以不是页面也可以接收通知会导致滥用，建议状态管理是基于页面来流转的，否则你需要写很多自定义的 Channel 方法
3. 这当然要如此才可以做到
4. 这样设计，避免 Android 的 Activity 销毁无法接收到页面通知，另外，页面出现的时候再收到通知，交互层面可以看到页面刷新的效果
5. 目前是不支持，Channel支持的类型就可以支持，主要是 dart 的序列化难以通过反射来实现，在 API 层面无法彻底解耦
6. 具体问题可以 issue

**Comment by czboosj** [comment]
项目引入 thrio 后,原项目 有RTRootNavigationController 库自定义的nav ,页面跳转循环调用崩溃,可能是两个都修改系统函数造成,暂时未深入进行查看

**Comment by foxsofter** [comment]
我暂时关闭了，如果有疑问尽管打开好了
thrio 没办法兼容所有场景，只能适合部分场景，将引入 Flutter 带来的成本降到最低，同时又不要引入太多不稳定性，取舍之间而已。现阶段没有时间支持更多场景了，比如 iOS 的 present，Android 的 Fragment，都不支持。主要是为了不引入太多问题。
