### ISSUE TITLE
抽时间来个swift的接入示例和文档吧，Android党表示看不懂OC

### ISSUE THREAD

**Issue by aBenVip** [flutter-thrio/thrio#91]
抽时间来个swift的接入示例和文档吧，Android党表示看不懂OC

**Comment by foxsofter** [comment]
暂时没时间提供Swift的demo

**Comment by foxsofter** [comment]
Swift 跟 kotlin 的语法已经很相近了，可以参考下，另外main分支上已经有 Swift 示例了
