### ISSUE TITLE
新建一个flutter项目 加入   thrio: '^0.5.0'  导致的问题

### ISSUE THREAD

**Issue by binbinyYang** [flutter-thrio/thrio#93]
新建一个flutter项目 加入   thrio: '^0.5.0'  导致的问题
kotlin版本 1.3.50
 gradle   classpath 'com.android.tools.build:gradle:3.5.0'
dart版本 193.7547
flutter版本50.0.1
distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip

为什么我的运行回报错

e: C:\flutter\.pub-cache\hosted\pub.flutter-io.cn\thrio-0.5.1\android\src\main\kotlin\io\flutter\embedding\android\ThrioFlutterView.kt: (601, 17): Type mismatch: inferred type is TextInputChannel but DartExecutor was expected
e: C:\flutter\.pub-cache\hosted\pub.flutter-io.cn\thrio-0.5.1\android\src\main\kotlin\io\flutter\embedding\android\ThrioFlutterView.kt: (604, 89): Too many arguments for public constructor AndroidTouchProcessor(@NonNull p0: FlutterRenderer) defined in io.flutter.embedding.android.AndroidTouchProcessor
e: C:\flutter\.pub-cache\hosted\pub.flutter-io.cn\thrio-0.5.1\android\src\main\kotlin\io\flutter\embedding\android\ThrioFlutterView.kt: (666, 53): Type mismatch: inferred type is TextInputChannel but DartExecutor was expected
e: C:\flutter\.pub-cache\hosted\pub.flutter-io.cn\thrio-0.5.1\android\src\main\kotlin\io\flutter\embedding\android\ThrioFlutterView.kt: (668, 76): Too many arguments for public constructor AndroidTouchProcessor(@NonNull p0: FlutterRenderer) defined in io.flutter.embedding.android.AndroidTouchProcessor

**Comment by binbinyYang** [comment]
e: C:\flutter\.pub-cache\hosted\pub.flutter-io.cn\thrio-0.5.1\android\src\main\kotlin\io\flutter\embedding\android\ThrioFlutterView.kt: (601, 17): Type mismatch: inferred type is TextInputChannel but DartExecutor was expected
e: C:\flutter\.pub-cache\hosted\pub.flutter-io.cn\thrio-0.5.1\android\src\main\kotlin\io\flutter\embedding\android\ThrioFlutterView.kt: (604, 89): Too many arguments for public constructor AndroidTouchProcessor(@NonNull p0: FlutterRenderer) defined in io.flutter.embedding.android.AndroidTouchProcessor
e: C:\flutter\.pub-cache\hosted\pub.flutter-io.cn\thrio-0.5.1\android\src\main\kotlin\io\flutter\embedding\android\ThrioFlutterView.kt: (666, 53): Type mismatch: inferred type is TextInputChannel but DartExecutor was expected
e: C:\flutter\.pub-cache\hosted\pub.flutter-io.cn\thrio-0.5.1\android\src\main\kotlin\io\flutter\embedding\android\ThrioFlutterView.kt: (668, 76): Too many arguments for public constructor AndroidTouchProcessor(@NonNull p0: FlutterRenderer) defined in io.flutter.embedding.android.AndroidTouchProcessor

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':thrio:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 30s
Exception: Gradle task assembleDebug failed with exit code 1


沒打全，以这个问准

**Comment by foxsofter** [comment]
Flutter SDK 1.22.x版本才能用现在的main分支，pub支持之前的版本，建议加QQ群，及时了解情况

**Comment by binbinyYang** [comment]
群号多少 我现在去加 我还有好几个问题

**Comment by foxsofter** [comment]
1014085473

**Comment by foxsofter** [comment]
版本不匹配的问题，关掉了
