### ISSUE TITLE
Flutter Master分支在Kotlin强类型下编译不通过

### ISSUE THREAD

**Issue by jiechic** [flutter-thrio/thrio#95]
![image](https://user-images.githubusercontent.com/518977/97657858-e7740b00-1aa5-11eb-90e5-4e8686942824.png)

看图，看对应的类，需要把“?”去掉

**Comment by jiechic** [comment]
![image](https://user-images.githubusercontent.com/518977/97658223-c2cc6300-1aa6-11eb-9bce-804592dbd156.png)
另一个类，同理。

**Comment by foxsofter** [comment]
已修复，main分支
