### ISSUE TITLE
关于Android原生端引入thrio进行Flutter编码的需求实现

### ISSUE THREAD

**Issue by jiechic** [flutter-thrio/thrio#96]
一般情况下，打个比方，现在使用的路由Arouter，一般来说，android开发的人员，会封装一层调用层routers
activity->routers-Arouter->activity2(getIntent获取参数)->return->activity(onActivityforresult获取结果)

如果把thrio作为Arouter下层

1、activity->routers-Arouter->thrio->activity2(getIntent获取参数)->return->activity(onActivityforresult获取结果)
那么这里，如果是activity2的原来getintent获取参数需要适配成原来的逻辑
并且这里onActivityForresult我不知道适配了没有（这里getIntent需要获得原来一模一样的数据结构，需要暴露一个方法可以给用户端使用，把接受的参数人为转换成为原来的参数格式）

2、这里还有一个问题，因为原生端的代码注册在arouter上，那么flutter端跳转原生端会有问题，因为没有注册在thrio上，所以也需要直接替换Arouter使用thrio作为路由注册。所以最后链路会变成
activity->routers->thrio->activity2(getIntent获取参数)->return->activity(onActivityforresult获取结果)
flutter路径就是
flutteractivity->thrio->activity2(getIntent获取参数)->return->flutteractivity(onActivityforresult获取结果)
flutter->thrio->activity2(getIntent获取参数)->return->flutter(futrue.then获取结果)

最少，getIntent和onActivitforresult的数据格式，需要暴露接口，让用户端可以还原成原来的数据结构，然后你在把对应的数据调用相应的方法 ，让原来的流程走下去。

是否保持统一的调用，一般本地会套有一层参数请求，用来切换路由组建，但是请求后的参数解析是每个界面都需要进行的，这一段在切换路由之后，必须保持一致，否在项目大的情况下，根本没法切换过来，也就没办法使用Flutter端

原生端需要使用混合路由的根本需要解决的问题是原生端打开页面是否能保证原来的参数格式能够得到解析而不用重新编码，该问题解决，才能通过混合路由引入Flutter端进行编码。

至于是否使用push和pop的三端统一，在原生端引入Flutter的场景下，不是强需求，因为各端会考虑封装一层去调用路由打开界面，或者写一个原路由的伪类，套到thrio路由上。

如果是一开始写代码，更没有三端统一的强需求，全部用Flutter写就好了。

**Comment by foxsofter** [comment]
以下几点是原因：
1. 在 thrio 设计阶段我就考虑过你说的问题，要不要兼容 Android 现有的 Activity 的套路，最终我选择了忽略，没有太多原因，参考
Flutter 的 Navigator 实现，谷歌自己已经做出改变，另外这套实现跟 iOS 的方式基本很好匹配。
2. Android 上现存的路由的方案，类似 ARouter 这种的，thrio 确实难以有多良好的兼容，只能尽量做到跟非 thrio 打开的
Activity 共存。
3. thrio 确实可以让三端都只使用这一套路由方案，但这不是根本要解决的问题，thrio 保证的是路由的跨端能力和一致性，至于从 Flutter
调起原生 Activity 还要实现兼容 onResult 并不是首要解决的问题。
以上，是 thrio 从最开始就放弃兼容 Activity 的 onResult 方案的原因。

戒尺 <notifications@github.com> 于2020年10月30日周五 下午8:47写道：

**Comment by foxsofter** [comment]
稳定性问题解决差不多，会考虑解决这个问题
